[pytest]
DJANGO_SETTINGS_MODULE = codeguard.settings.test
python_files = tests.py test_*.py *_tests.py
addopts = --tb=short -v
testpaths = tests
markers =
    live_judge0: Tests requiring a live Judge0 sandbox service

