# Generated by Django 5.1.15 on 2026-09-02 17:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_type', models.CharField(choices=[('RUN', 'Run Code (Public Test Cases)'), ('SUBMIT', 'Submit Solution (Authoritative Evaluation)')], max_length=16)),
                ('source_code', models.TextField()),
                ('language', models.CharField(max_length=32)),
                ('environment_version', models.CharField(default='CG-ENV-PY311-V1', help_text='Immutable compiler/runtime environment version used.', max_length=64)),
                ('execution_policy_version', models.CharField(default='CG-EXEC-V1', help_text='Immutable execution resource policy schema version used.', max_length=64)),
                ('comparison_policy_version', models.CharField(default='CG-CMP-V1', help_text='Immutable output comparison algorithm version used.', max_length=64)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued for Execution'), ('PROCESSING', 'Processing Submission'), ('COMPILING', 'Compiling Source Code'), ('RUNNING', 'Running Test Cases'), ('EVALUATING', 'Evaluating Outputs'), ('COMPLETED', 'Execution Completed'), ('FAILED', 'System Infrastructure Failure'), ('CANCELLED', 'Cancelled')], db_index=True, default='QUEUED', max_length=20)),
                ('verdict', models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('TIME_LIMIT_EXCEEDED', 'Time Limit Exceeded'), ('MEMORY_LIMIT_EXCEEDED', 'Memory Limit Exceeded'), ('COMPILATION_ERROR', 'Compilation Error'), ('RUNTIME_ERROR', 'Runtime Error'), ('OUTPUT_LIMIT_EXCEEDED', 'Output Limit Exceeded'), ('SYSTEM_ERROR', 'System Error')], db_index=True, max_length=32, null=True)),
                ('total_test_cases', models.PositiveIntegerField(default=0)),
                ('passed_test_cases', models.PositiveIntegerField(default=0)),
                ('score_awarded', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('max_score', models.PositiveIntegerField(default=0)),
                ('execution_time_ms', models.PositiveIntegerField(default=0, help_text='Maximum CPU execution time across all test cases (ms)')),
                ('memory_used_kb', models.PositiveIntegerField(default=0, help_text='Maximum resident set memory used across all test cases (KB)')),
                ('compilation_error', models.TextField(blank=True, default='', help_text='Sanitized compiler error log (if compilation failed)')),
                ('idempotency_key', models.CharField(db_index=True, max_length=128)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_submissions', to='assessments.testattempt')),
                ('snapshot_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='code_submissions', to='assessments.assessmentsnapshotquestion')),
            ],
            options={
                'db_table': 'code_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CodeTestCaseResult',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('test_case_index', models.PositiveIntegerField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('verdict', models.CharField(choices=[('PASSED', 'Passed'), ('FAILED', 'Failed'), ('TIME_LIMIT_EXCEEDED', 'Time Limit Exceeded'), ('MEMORY_LIMIT_EXCEEDED', 'Memory Limit Exceeded'), ('RUNTIME_ERROR', 'Runtime Error')], max_length=32)),
                ('points_awarded', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('max_points', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('execution_time_ms', models.PositiveIntegerField(default=0)),
                ('memory_used_kb', models.PositiveIntegerField(default=0)),
                ('public_input', models.TextField(blank=True, null=True)),
                ('expected_output', models.TextField(blank=True, null=True)),
                ('actual_output', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_case_results', to='evaluator.codesubmission')),
            ],
            options={
                'db_table': 'code_test_case_results',
                'ordering': ['submission', 'test_case_index'],
            },
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['attempt', 'snapshot_question', '-created_at'], name='idx_subm_att_q'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['idempotency_key', 'status'], name='idx_subm_idemp_st'),
        ),
        migrations.AddIndex(
            model_name='codesubmission',
            index=models.Index(fields=['attempt', 'status'], name='idx_subm_att_st'),
        ),
        migrations.AddConstraint(
            model_name='codetestcaseresult',
            constraint=models.UniqueConstraint(fields=('submission', 'test_case_index'), name='unique_submission_tc_index'),
        ),
    ]
