# Generated by Django 5.1.15 on 2026-09-06 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesubmission',
            name='verdict',
            field=models.CharField(blank=True, choices=[('ACCEPTED', 'Accepted'), ('WRONG_ANSWER', 'Wrong Answer'), ('TIME_LIMIT_EXCEEDED', 'Time Limit Exceeded'), ('MEMORY_LIMIT_EXCEEDED', 'Memory Limit Exceeded'), ('COMPILATION_ERROR', 'Compilation Error'), ('RUNTIME_ERROR', 'Runtime Error'), ('OUTPUT_LIMIT_EXCEEDED', 'Output Limit Exceeded'), ('SYSTEM_ERROR', 'System Error'), ('SYNTAX_ERROR', 'Syntax Error'), ('UNSAFE_QUERY', 'Unsafe Query')], db_index=True, max_length=32, null=True),
        ),
    ]
