# Generated by Django 5.1.15 on 2026-09-03 06:17

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_assessment_passing_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCleanupQueue',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_id', models.UUIDField(db_index=True)),
                ('file_path', models.CharField(max_length=512)),
                ('file_bytes', models.BigIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Unlink'), ('CONFIRMED', 'Confirmed Deleted'), ('RETRYING', 'Retrying After Error'), ('FAILED', 'Failed Permanently')], default='PENDING', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('confirmed_deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'retention_file_cleanup_queue',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='idx_file_cleanup_status'), models.Index(fields=['attempt_id', 'status'], name='idx_file_cleanup_attempt')],
            },
        ),
        migrations.CreateModel(
            name='PurgeJobRun',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('trigger_type', models.CharField(choices=[('SCHEDULED_DAILY', 'Scheduled Daily Task'), ('MANUAL_ADMIN', 'Manual Administrator Purge')], max_length=20)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='RUNNING', max_length=20)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attempts_evaluated_count', models.PositiveIntegerField(default=0)),
                ('attempts_purged_count', models.PositiveIntegerField(default=0)),
                ('attempts_deferred_hold_count', models.PositiveIntegerField(default=0)),
                ('attempts_deferred_export_count', models.PositiveIntegerField(default=0)),
                ('total_bytes_reclaimed', models.BigIntegerField(default=0)),
                ('error_summary', models.TextField(blank=True)),
                ('operator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='executed_purge_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retention_purge_job_runs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.PositiveIntegerField(default=1)),
                ('scope', models.CharField(choices=[('INSTITUTION', 'Institution-Wide'), ('ASSESSMENT', 'Assessment-Specific')], default='INSTITUTION', max_length=20)),
                ('detailed_data_ttl_days', models.PositiveIntegerField(default=30, help_text='Days after submission until detailed answers, code, and keyframes expire.')),
                ('proctoring_evidence_ttl_days', models.PositiveIntegerField(default=30, help_text='Days after submission until proctoring webcam keyframes and evidence expire.')),
                ('report_retention_ttl_days', models.PositiveIntegerField(default=7, help_text='Days generated compliance reports remain accessible.')),
                ('is_active', models.BooleanField(default=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='retention_policies', to='assessments.assessment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_retention_policies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retention_policies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('policy_version', models.PositiveIntegerField(editable=False)),
                ('detailed_data_expires_at', models.DateTimeField(db_index=True)),
                ('proctoring_evidence_expires_at', models.DateTimeField(db_index=True)),
                ('purge_state', models.CharField(choices=[('SCHEDULED', 'Scheduled for Purge'), ('DEFERRED_HOLD', 'Deferred: Active Legal Hold'), ('DEFERRED_EXPORT', 'Deferred: In-Flight DSAR Export'), ('SCRUBBING_DB', 'Scrubbing Database Telemetry'), ('CLEANING_FILES', 'Unlinking Filesystem Evidence'), ('PURGED', 'Completely Purged & Tombstoned')], default='SCHEDULED', max_length=25)),
                ('database_scrub_status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('filesystem_cleanup_status', models.CharField(choices=[('PENDING', 'Pending Unlink'), ('CONFIRMED', 'Confirmed Deleted'), ('RETRYING', 'Retrying After Error'), ('FAILED', 'Failed Permanently')], default='PENDING', max_length=20)),
                ('last_scrubbed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retention_record', to='assessments.testattempt')),
                ('retention_policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='retention_records', to='retention.retentionpolicy')),
            ],
            options={
                'db_table': 'retention_records',
                'ordering': ['detailed_data_expires_at'],
            },
        ),
        migrations.CreateModel(
            name='RetentionTombstone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_id', models.UUIDField(editable=False, unique=True)),
                ('student_id', models.UUIDField(editable=False)),
                ('student_euid', models.CharField(editable=False, help_text='Retained strictly pursuant to documented institutional accreditation & transcript audit requirements.', max_length=64)),
                ('assessment_id', models.UUIDField(editable=False)),
                ('assessment_title_snapshot', models.CharField(editable=False, max_length=255)),
                ('purged_at', models.DateTimeField(editable=False)),
                ('purged_by_system', models.BooleanField(default=True, editable=False)),
                ('answers_scrubbed_count', models.PositiveIntegerField(editable=False)),
                ('code_submissions_scrubbed_count', models.PositiveIntegerField(editable=False)),
                ('proctoring_events_scrubbed_count', models.PositiveIntegerField(editable=False)),
                ('evidence_files_deleted_count', models.PositiveIntegerField(editable=False)),
                ('confirmed_bytes_reclaimed', models.BigIntegerField(editable=False)),
                ('sha256_audit_proof', models.CharField(editable=False, help_text='HMAC-SHA256 keyed integrity and authenticity proof.', max_length=64)),
                ('operator_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='triggered_tombstones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retention_tombstones',
                'ordering': ['-purged_at'],
            },
        ),
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('REQUESTED', 'Export Requested'), ('SNAPSHOT_PENDING', 'Acquiring Consistent Snapshot'), ('SNAPSHOT_ACQUIRED', 'Snapshot Acquired (Protected from Purge)'), ('GENERATING', 'Encrypting & Packaging Archive'), ('READY', 'Ready for Download'), ('EXPIRED', 'Archive Expired & Deleted'), ('FAILED', 'Generation Failed')], default='REQUESTED', max_length=25)),
                ('archive_type', models.CharField(choices=[('FULL_PRE_PURGE_TELEMETRY', 'Full Pre-Purge Student Telemetry'), ('AVAILABLE_PARTIAL_ARCHIVE', 'Post-Purge Academic Summary & Tombstone')], default='FULL_PRE_PURGE_TELEMETRY', max_length=35)),
                ('snapshot_payload', models.JSONField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Bounded lease expiration (15m default). SNAPSHOT_PENDING only protects while lease_expires_at > now().', null=True)),
                ('encryption_algorithm', models.CharField(default='AES-256-GCM', max_length=25)),
                ('encryption_key_version', models.CharField(default='v1', max_length=20)),
                ('nonce_hex', models.CharField(blank=True, max_length=32)),
                ('auth_tag_hex', models.CharField(blank=True, max_length=32)),
                ('file_path', models.CharField(blank=True, max_length=512)),
                ('file_bytes', models.BigIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dsar_export_jobs', to='assessments.testattempt')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dsar_export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retention_export_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status'], name='idx_export_student_stat'), models.Index(fields=['attempt', 'status'], name='idx_export_attempt_stat'), models.Index(fields=['status', 'lease_expires_at'], name='idx_export_stat_lease'), models.Index(fields=['expires_at'], name='idx_export_expires_at')],
            },
        ),
        migrations.CreateModel(
            name='LegalHold',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('case_reference', models.CharField(db_index=True, max_length=100)),
                ('reason', models.TextField()),
                ('scope', models.CharField(choices=[('ATTEMPT', 'Specific Test Attempt'), ('STUDENT', 'All Attempts by Student'), ('ASSESSMENT', 'All Attempts in Assessment')], max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active & Enforcing Hold'), ('RELEASED', 'Released')], default='ACTIVE', max_length=20)),
                ('placed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('release_reason', models.TextField(blank=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessment_legal_holds', to='assessments.assessment')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legal_holds', to='assessments.testattempt')),
                ('placed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placed_legal_holds', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='released_legal_holds', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_legal_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'retention_legal_holds',
                'ordering': ['-placed_at'],
                'indexes': [models.Index(fields=['scope', 'status'], name='idx_hold_scope_status'), models.Index(fields=['attempt', 'status'], name='idx_hold_attempt_stat'), models.Index(fields=['student', 'status'], name='idx_hold_student_stat'), models.Index(fields=['assessment', 'status'], name='idx_hold_assessment_stat')],
            },
        ),
        migrations.AddConstraint(
            model_name='retentionpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('detailed_data_ttl_days__gte', 1), ('detailed_data_ttl_days__lte', 3650)), name='chk_detailed_ttl_range'),
        ),
        migrations.AddConstraint(
            model_name='retentionpolicy',
            constraint=models.CheckConstraint(condition=models.Q(('proctoring_evidence_ttl_days__gte', 1), ('proctoring_evidence_ttl_days__lte', 3650)), name='chk_evidence_ttl_range'),
        ),
        migrations.AddIndex(
            model_name='retentionrecord',
            index=models.Index(fields=['purge_state', 'detailed_data_expires_at'], name='idx_retention_purge_exp'),
        ),
        migrations.AddIndex(
            model_name='retentiontombstone',
            index=models.Index(fields=['attempt_id'], name='idx_tombstone_attempt'),
        ),
        migrations.AddIndex(
            model_name='retentiontombstone',
            index=models.Index(fields=['student_euid'], name='idx_tombstone_euid'),
        ),
        migrations.AddIndex(
            model_name='retentiontombstone',
            index=models.Index(fields=['assessment_id'], name='idx_tombstone_assessment'),
        ),
        migrations.AddIndex(
            model_name='retentiontombstone',
            index=models.Index(fields=['purged_at'], name='idx_tombstone_purged_at'),
        ),
    ]
