# Generated by Django 5.1.15 on 2026-09-02 17:47

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctoringSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('TERMINATED', 'Terminated'), ('DEGRADED', 'Degraded')], db_index=True, default='ACTIVE', max_length=20)),
                ('risk_score', models.DecimalField(db_index=True, decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('risk_band', models.CharField(choices=[('NORMAL', 'Normal (0-20)'), ('LOW', 'Low (21-45)'), ('MEDIUM', 'Medium (46-70)'), ('HIGH', 'High (71-85)'), ('CRITICAL', 'Critical (86-100)')], db_index=True, default='NORMAL', max_length=20)),
                ('total_events_count', models.PositiveIntegerField(default=0)),
                ('total_warnings_count', models.PositiveIntegerField(default=0)),
                ('review_status', models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('UNDER_REVIEW', 'Under Review'), ('REVIEWED', 'Reviewed'), ('DISMISSED', 'Dismissed'), ('ESCALATED', 'Escalated')], db_index=True, default='UNREVIEWED', max_length=20)),
                ('attempt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_session', to='assessments.testattempt')),
            ],
            options={
                'db_table': 'proctoring_sessions',
            },
        ),
        migrations.CreateModel(
            name='ProctoringReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('REVIEWED_CLEAN', 'Reviewed - Clean / Normal'), ('SUSPICIOUS_CONFIRMED', 'Suspicious Behavior Confirmed'), ('DISMISSED_FALSE_POSITIVE', 'Dismissed as False Positive'), ('REQUIRES_FURTHER_INSPECTION', 'Requires Further Inspection')], default='REVIEWED_CLEAN', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proctoring_reviews', to=settings.AUTH_USER_MODEL)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='proctoring.proctoringsession')),
            ],
            options={
                'db_table': 'proctoring_reviews',
            },
        ),
        migrations.CreateModel(
            name='ProctoringEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('media_type', models.CharField(choices=[('IMAGE_JPEG', 'JPEG Image Keyframe'), ('AUDIO_WEBM', 'WebM Opus Audio Snippet')], default='IMAGE_JPEG', max_length=32)),
                ('storage_path', models.CharField(max_length=512)),
                ('sha256_hash', models.CharField(max_length=64)),
                ('file_size_bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('retention_class', models.CharField(choices=[('EPHEMERAL_BUFFER', 'Ephemeral Buffer (0s)'), ('TEMPORARY_EVIDENCE', 'Temporary Flagged Evidence (30d)'), ('OPERATIONAL_AUDIT', 'Operational Audit Ledger (90d)'), ('PERMANENT_RECORD', 'Permanent Academic Summary')], db_index=True, default='TEMPORARY_EVIDENCE', max_length=32)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='proctoring.proctoringsession')),
            ],
            options={
                'db_table': 'proctoring_evidences',
            },
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('source', models.CharField(choices=[('BROWSER', 'Browser Client Telemetry'), ('AI', 'Asynchronous AI Inference'), ('SERVER', 'Authoritative Server State'), ('SYSTEM', 'System Infrastructure')], db_index=True, default='BROWSER', max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', max_length=20)),
                ('confidence', models.FloatField(default=1.0)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('client_detected_at', models.DateTimeField(blank=True, null=True)),
                ('server_received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('model_name', models.CharField(blank=True, default='', max_length=64)),
                ('model_version', models.CharField(blank=True, default='', max_length=32)),
                ('threshold_version', models.CharField(default='V1', max_length=32)),
                ('inference_policy_version', models.CharField(default='V1', max_length=32)),
                ('risk_delta', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='proctoring.proctoringevidence')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='proctoring.proctoringsession')),
            ],
            options={
                'db_table': 'proctoring_events',
                'ordering': ['server_received_at'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringWarning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('warning_type', models.CharField(db_index=True, max_length=64)),
                ('message', models.CharField(max_length=255)),
                ('issued_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warnings', to='proctoring.proctoringsession')),
            ],
            options={
                'db_table': 'proctoring_warnings',
            },
        ),
        migrations.AddIndex(
            model_name='proctoringsession',
            index=models.Index(fields=['attempt', 'status'], name='idx_proct_attempt_status'),
        ),
        migrations.AddIndex(
            model_name='proctoringsession',
            index=models.Index(fields=['risk_band', 'review_status'], name='idx_proct_risk_review'),
        ),
        migrations.AddIndex(
            model_name='proctoringevidence',
            index=models.Index(fields=['session', 'created_at'], name='idx_evidence_session_time'),
        ),
        migrations.AddIndex(
            model_name='proctoringevidence',
            index=models.Index(fields=['retention_class', 'expires_at'], name='idx_evidence_retention_expiry'),
        ),
        migrations.AddIndex(
            model_name='proctoringevent',
            index=models.Index(fields=['session', 'server_received_at'], name='idx_event_session_recv_time'),
        ),
        migrations.AddIndex(
            model_name='proctoringevent',
            index=models.Index(fields=['session', 'event_type'], name='idx_event_session_type'),
        ),
        migrations.AddIndex(
            model_name='proctoringevent',
            index=models.Index(fields=['event_type', 'server_received_at'], name='idx_event_type_time'),
        ),
        migrations.AddIndex(
            model_name='proctoringwarning',
            index=models.Index(fields=['session', 'issued_at'], name='idx_warning_session_time'),
        ),
    ]
