# Generated by Django 5.1.15 on 2026-09-03 10:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_assessment_passing_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProctorDutySession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('active_monitored_count', models.PositiveIntegerField(default=0, help_text='Number of active student attempts monitored during this shift.')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_duty_sessions', to='assessments.assessment')),
                ('proctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duty_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctor_duty_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ProctorAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether the proctor is currently on active duty.')),
                ('max_candidates', models.PositiveIntegerField(default=30, help_text='Configurable operational capacity limit (default 30 candidates per proctor).')),
                ('notes', models.TextField(blank=True, default='', help_text='Administrative notes regarding the duty assignment.')),
                ('assessment', models.ForeignKey(help_text='Target assessment cohort.', on_delete=django.db.models.deletion.CASCADE, related_name='proctor_assignments', to='assessments.assessment')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proctor_assignments_created', to=settings.AUTH_USER_MODEL)),
                ('proctor', models.ForeignKey(help_text='User with PROCTOR or ADMIN role.', on_delete=django.db.models.deletion.CASCADE, related_name='proctor_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctor_assignments',
                'indexes': [models.Index(fields=['assessment', 'is_active'], name='idx_proct_assign_active')],
                'constraints': [models.UniqueConstraint(fields=('proctor', 'assessment'), name='unique_proctor_assessment_assignment')],
            },
        ),
        migrations.CreateModel(
            name='ProctorChatMessage',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_text', models.TextField(help_text='Student-facing chat content. Excludes internal investigation remarks.')),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctor_chat_messages', to='assessments.testattempt')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_proctor_chats', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_proctor_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctor_chat_messages',
                'ordering': ['sent_at'],
                'indexes': [models.Index(fields=['attempt', 'sent_at'], name='idx_proct_chat_att_time')],
            },
        ),
        migrations.CreateModel(
            name='ProctorIntervention',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('WARNING_ISSUED', 'Warning Issued'), ('WARNING_ACKNOWLEDGED', 'Warning Acknowledged'), ('PAUSE_STARTED', 'Pause Started'), ('PAUSE_ENDED', 'Pause Ended'), ('ROOM_SCAN_REQUESTED', 'Room Scan Requested'), ('ROOM_SCAN_COMPLETED', 'Room Scan Completed'), ('TERMINATION_REQUESTED', 'Termination Requested')], db_index=True, max_length=40)),
                ('reason_code', models.CharField(blank=True, default='', help_text='Machine-readable reason code (e.g. MULTIPLE_FACES, SUSPICIOUS_AUDIO, DISQUALIFICATION_CAUSE).', max_length=64)),
                ('reason_text', models.TextField(blank=True, default='', help_text='Candidate-visible justification or warning message.')),
                ('internal_notes', models.TextField(blank=True, default='', help_text='Restricted proctor/admin investigation remarks. Strictly excluded from student DSAR exports.')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Structured operational telemetry (e.g. snapshot risk band, client latency, duration_seconds).')),
                ('request_idempotency_key', models.CharField(blank=True, db_index=True, default='', help_text='Client-supplied or server-generated idempotency key preventing duplicate dispatches.', max_length=128)),
                ('issued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Authoritative server timestamp when the intervention occurred.')),
                ('attempt', models.ForeignKey(help_text='Target test attempt.', on_delete=django.db.models.deletion.CASCADE, related_name='proctor_interventions', to='assessments.testattempt')),
                ('parent_event', models.ForeignKey(blank=True, help_text='Links lifecycle pairs (e.g. PAUSE_ENDED links to PAUSE_STARTED; ACK links to WARNING).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_events', to='invigilation.proctorintervention')),
                ('proctor', models.ForeignKey(blank=True, help_text='Acting human proctor (null for student actions like acknowledgement).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issued_interventions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(help_text='Target candidate.', on_delete=django.db.models.deletion.PROTECT, related_name='student_interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'proctor_interventions',
                'ordering': ['issued_at'],
                'indexes': [models.Index(fields=['attempt', 'event_type'], name='idx_proct_interv_att_type'), models.Index(fields=['attempt', 'issued_at'], name='idx_proct_interv_att_time'), models.Index(fields=['request_idempotency_key'], name='idx_proct_interv_idempotent')],
            },
        ),
    ]
