# Generated by Django 5.1.15 on 2026-09-03 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invigilation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proctorintervention',
            name='event_type',
            field=models.CharField(choices=[('WARNING_ISSUED', 'Warning Issued'), ('WARNING_ACKNOWLEDGED', 'Warning Acknowledged'), ('PAUSE_STARTED', 'Pause Started'), ('PAUSE_ENDED', 'Pause Ended'), ('ROOM_SCAN_REQUESTED', 'Room Scan Requested'), ('ROOM_SCAN_COMPLETED', 'Room Scan Completed'), ('TERMINATION_REQUESTED', 'Termination Requested'), ('TERMINATION_CONFIRMED', 'Termination Confirmed')], db_index=True, max_length=40),
        ),
    ]
