# Generated by Django 5.1.15 on 2026-09-02 16:12

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64, unique=True)),
                ('slug', models.SlugField(max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('MULTI_SELECT', 'Multiple Select Question'), ('TRUE_FALSE', 'True / False Question'), ('SHORT_ANSWER', 'Short Answer Question'), ('CODING', 'Coding Question'), ('SQL', 'SQL Query Question')], db_index=True, editable=False, max_length=32)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='ACTIVE', max_length=16)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionVersion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField()),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('MULTI_SELECT', 'Multiple Select Question'), ('TRUE_FALSE', 'True / False Question'), ('SHORT_ANSWER', 'Short Answer Question'), ('CODING', 'Coding Question'), ('SQL', 'SQL Query Question')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(help_text='Markdown problem statement / prompt')),
                ('instructions', models.TextField(blank=True, default='')),
                ('points', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(1)])),
                ('negative_marking_enabled', models.BooleanField(default=False)),
                ('negative_points', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, default='MEDIUM', max_length=16)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=16)),
                ('type_config', models.JSONField(blank=True, default=dict, help_text='Structured type-specific options and matching rules')),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_question_versions', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='questions.question')),
                ('tags', models.ManyToManyField(blank=True, related_name='question_versions', to='questions.tag')),
            ],
            options={
                'ordering': ['version_number'],
                'unique_together': {('question', 'version_number')},
            },
        ),
        migrations.CreateModel(
            name='CodingQuestionConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_statement', models.TextField()),
                ('input_description', models.TextField(blank=True, default='')),
                ('output_description', models.TextField(blank=True, default='')),
                ('constraints', models.TextField(blank=True, default='')),
                ('allowed_languages', models.JSONField(default=list, help_text="List of permitted languages e.g. ['PYTHON', 'CPP', 'JAVA']")),
                ('time_limit_ms', models.PositiveIntegerField(default=2000, help_text='Execution time limit in milliseconds')),
                ('memory_limit_mb', models.PositiveIntegerField(default=256, help_text='Memory limit in megabytes')),
                ('question_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coding_config', to='questions.questionversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SQLQuestionConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('problem_statement', models.TextField()),
                ('schema_setup_sql', models.TextField(help_text='DDL/DML SQL statements to construct sandbox tables and seed rows')),
                ('expected_result_definition', models.TextField(help_text='Reference target query or tabular result specification')),
                ('allowed_dialect', models.CharField(default='MYSQL', max_length=32)),
                ('time_limit_ms', models.PositiveIntegerField(default=3000)),
                ('question_version', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sql_config', to='questions.questionversion')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('points', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden evaluation test case (never leaked to student-facing endpoints)')),
                ('execution_order', models.PositiveIntegerField(default=1)),
                ('time_limit_override_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('memory_limit_override_mb', models.PositiveIntegerField(blank=True, null=True)),
                ('coding_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='questions.codingquestionconfig')),
            ],
            options={
                'ordering': ['execution_order', 'created_at'],
            },
        ),
    ]
