# Generated by Django 5.1.15 on 2026-09-05 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='codingquestionconfig',
            name='examples',
            field=models.JSONField(blank=True, default=list, help_text="List of example cases: [{'input': '...', 'output': '...', 'explanation': '...'}]"),
        ),
        migrations.AddField(
            model_name='codingquestionconfig',
            name='reference_solution_hash',
            field=models.CharField(blank=True, default='', help_text='SHA-256 hash of verified reference solution source and language', max_length=64),
        ),
        migrations.AddField(
            model_name='codingquestionconfig',
            name='reference_solution_language',
            field=models.CharField(blank=True, default='', help_text='Primary verified reference solution language', max_length=32),
        ),
        migrations.AddField(
            model_name='codingquestionconfig',
            name='reference_solution_verified',
            field=models.BooleanField(default=False, help_text='Whether the reference solution has been verified against all test cases'),
        ),
        migrations.AddField(
            model_name='codingquestionconfig',
            name='reference_solution_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the reference solution was verified', null=True),
        ),
        migrations.AddField(
            model_name='codingquestionconfig',
            name='reference_solutions',
            field=models.JSONField(blank=True, default=dict, help_text='Admin reference solutions: {language: code}'),
        ),
        migrations.AddField(
            model_name='codingquestionconfig',
            name='starter_codes',
            field=models.JSONField(blank=True, default=dict, help_text="Mapping of language key to starter code e.g. {'PYTHON': '...'}"),
        ),
        migrations.AddField(
            model_name='testcase',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Whether the expected output has been explicitly verified by an administrator'),
        ),
        migrations.AddField(
            model_name='testcase',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Test case name or label', max_length=128),
        ),
    ]
