# Generated by Django 5.1.15 on 2026-09-02 14:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(db_index=True, max_length=64, verbose_name='Action Type')),
                ('target_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='Target Entity Type')),
                ('target_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Target Entity ID')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Event Metadata')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Acting User')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['action', 'created_at'], name='accounts_au_action_c683b9_idx'), models.Index(fields=['actor', 'created_at'], name='accounts_au_actor_i_670b11_idx'), models.Index(fields=['target_type', 'target_id'], name='accounts_au_target__0c7dca_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roll_number', models.CharField(db_index=True, help_text='Unique student registration/roll number.', max_length=64, unique=True, verbose_name='Academic Roll Number')),
                ('euid', models.CharField(db_index=True, help_text='Deterministic, collision-safe exam unique identifier.', max_length=64, unique=True, verbose_name='Exam Unique ID (EUID)')),
                ('first_login_required', models.BooleanField(db_index=True, default=True, help_text='Mandates immediate password reset before student can access platform assessments.', verbose_name='First Login Password Change Required')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL, verbose_name='Associated User')),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['roll_number'], name='accounts_st_roll_nu_9eff1d_idx'), models.Index(fields=['euid'], name='accounts_st_euid_88dd58_idx'), models.Index(fields=['first_login_required'], name='accounts_st_first_l_91ae20_idx')],
            },
        ),
    ]
