# Generated by Django 5.1.15 on 2026-09-03 18:48

from django.db import migrations, models


def populate_admin_ids(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    admins = list(User.objects.filter(role='ADMIN').order_by('created_at', 'id'))
    if not admins:
        return
    for idx, admin in enumerate(admins):
        if idx == 0 or admin.email in ('gauravagldeveloper28@gmail.com', 'admin@codeguard.local'):
            admin.admin_id = 'EUAD-GAURAV-099'
        else:
            admin.admin_id = f"CG-ADM-{max(2, idx + 1):06d}"
        admin.save(update_fields=['admin_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog_studentprofile'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Authoritative unique administrative identifier.', max_length=64, verbose_name='Admin ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('STUDENT', 'Student'), ('PROCTOR', 'Proctor')], db_index=True, default='STUDENT', max_length=20, verbose_name='User Role'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['admin_id'], name='accounts_us_admin_i_470f06_idx'),
        ),
        migrations.RunPython(populate_admin_ids, migrations.RunPython.noop),
    ]
