# Generated by Django 5.1.15 on 2026-09-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_admin_id_alter_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login_required',
            field=models.BooleanField(db_index=True, default=False, help_text='Mandates password change upon next login.', verbose_name='First Login Password Change Required'),
        ),
    ]
