# Generated by Django 5.1.15 on 2026-09-04 05:20

import uuid
from django.db import migrations, models


def reconcile_admin_identities(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    AdminSequence = apps.get_model('accounts', 'AdminSequence')

    # 1. Ensure Canonical Primary Admin
    primary_admin = User.objects.filter(email='gauravagldeveloper28@gmail.com').first()
    if primary_admin:
        primary_admin.admin_id = 'EUAD-GAURAV-099'
        primary_admin.display_name = 'Gaurav Agarwal'
        primary_admin.role = 'ADMIN'
        primary_admin.first_login_required = False
        primary_admin.save(update_fields=['admin_id', 'display_name', 'role', 'first_login_required'])

    # 2. Reconcile secondary/default admin
    secondary_admin = User.objects.filter(email='admin@codeguard.local').first()
    if secondary_admin:
        secondary_admin.admin_id = 'CG-ADM-000002'
        secondary_admin.display_name = 'System Administrator'
        secondary_admin.role = 'ADMIN'
        secondary_admin.first_login_required = False
        secondary_admin.save(update_fields=['admin_id', 'display_name', 'role', 'first_login_required'])

    # 3. Ensure other existing admins have unique IDs starting from 3
    other_admins = User.objects.filter(role='ADMIN').exclude(
        email__in=['gauravagldeveloper28@gmail.com', 'admin@codeguard.local']
    ).order_by('created_at', 'id')

    next_seq = 3
    for admin in other_admins:
        if not admin.admin_id or admin.admin_id in ('EUAD-GAURAV-099', 'CG-ADM-000001', 'CG-ADM-000002'):
            admin.admin_id = f"CG-ADM-{next_seq:06d}"
            next_seq += 1
        if not admin.display_name:
            admin.display_name = admin.email.split('@')[0].replace('.', ' ').title()
        admin.save(update_fields=['admin_id', 'display_name'])

    # 4. Initialize AdminSequence
    seq_obj, _ = AdminSequence.objects.get_or_create(
        id=uuid.UUID('00000000-0000-0000-0000-000000000001'),
        defaults={'last_sequence': max(next_seq, 3)}
    )
    if seq_obj.last_sequence < next_seq:
        seq_obj.last_sequence = next_seq
        seq_obj.save(update_fields=['last_sequence'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_first_login_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sequence', models.PositiveIntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Admin Sequence',
                'verbose_name_plural': 'Admin Sequences',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='Authoritative user display name.', max_length=255, verbose_name='Display Name'),
        ),
        migrations.RunPython(reconcile_admin_identities, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'ADMIN'), models.Q(('admin_id', ''), _negated=True)), fields=('admin_id',), name='unique_admin_id_for_admins'),
        ),
    ]
