# Generated by Django 5.1.15 on 2026-09-05 13:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_admin_identity_immutability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, help_text='Unique normalized academic section code (e.g. AIML-A, CSE-B).', max_length=32, unique=True, verbose_name='Section Code')),
                ('name', models.CharField(help_text='Human-readable section title (e.g. Artificial Intelligence & Machine Learning Section A).', max_length=128, verbose_name='Section Name')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Designates whether this section is active for new student enrollment and assessment targeting.', verbose_name='Is Active')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='accounts_se_code_a241fc_idx')],
            },
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='section',
            field=models.ForeignKey(blank=True, help_text='Academic section classification for student.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.section', verbose_name='Academic Section'),
        ),
        migrations.AddIndex(
            model_name='studentprofile',
            index=models.Index(fields=['section'], name='accounts_st_section_79f8f1_idx'),
        ),
    ]
