# Generated by Django 5.1.15 on 2026-09-06 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_section_studentprofile_section_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique_admin_id_for_admins',
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(models.Case(models.When(models.Q(('role', 'ADMIN'), models.Q(('admin_id', ''), _negated=True)), then=models.F('admin_id')), default=models.Value(None), output_field=models.CharField(max_length=64, null=True)), name='unique_admin_id_for_admins'),
        ),
    ]
