# Generated by Django 5.1.15 on 2026-09-02 16:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('start_datetime', models.DateTimeField(db_index=True)),
                ('end_datetime', models.DateTimeField(db_index=True)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration allocated per attempt in minutes.', validators=[django.core.validators.MinValueValidator(1)])),
                ('total_points', models.PositiveIntegerField(default=0, help_text='Total marks for the assessment. Must equal SUM(AssessmentQuestion.points) at publish time.')),
                ('negative_marking_enabled', models.BooleanField(default=False, help_text='Global switch allowing negative marking on questions in this assessment.')),
                ('attempt_limit', models.PositiveIntegerField(default=1, help_text='Maximum number of attempts allowed per student.', validators=[django.core.validators.MinValueValidator(1)])),
                ('randomize_questions', models.BooleanField(default=False, help_text='If enabled, questions are presented in deterministic pseudo-random order per attempt.')),
                ('randomize_options', models.BooleanField(default=False, help_text='If enabled, MCQ/Multi-select options are shuffled deterministically per attempt.')),
                ('result_visibility', models.CharField(choices=[('IMMEDIATE', 'Immediate'), ('AFTER_DEADLINE', 'After Deadline'), ('MANUAL', 'Manual Release')], default='AFTER_DEADLINE', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_assessments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAssignment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('ASSIGNED', 'Assigned'), ('REVOKED', 'Revoked')], db_index=True, default='ASSIGNED', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='assessments.assessment')),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assigned_assessments_by', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'assessment_assignments',
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=1)),
                ('points', models.PositiveIntegerField(default=10, help_text='Points assigned to this question in this assessment.', validators=[django.core.validators.MinValueValidator(1)])),
                ('negative_marking_enabled', models.BooleanField(default=False, help_text='If enabled for this question (and globally enabled), incorrect answers receive penalty.')),
                ('negative_points', models.PositiveIntegerField(default=0, help_text='Points deducted for incorrect answers.')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='assessments.assessment')),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_associations', to='questions.questionversion')),
            ],
            options={
                'db_table': 'assessment_questions',
                'ordering': ['assessment', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentSnapshot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('snapshot_data', models.JSONField(default=dict, help_text='Complete student-safe frozen payload: metadata, questions, public test cases.')),
                ('server_evaluation_bundle', models.JSONField(default=dict, help_text='Server-only evaluation payload: hidden test cases, expected answers/queries. NEVER exposed to students.')),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot', to='assessments.assessment')),
            ],
            options={
                'db_table': 'assessment_snapshots',
            },
        ),
        migrations.CreateModel(
            name='AssessmentSnapshotQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_question_id', models.CharField(db_index=True, max_length=64)),
                ('order', models.PositiveIntegerField(default=1)),
                ('question_type', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('instructions', models.TextField(blank=True, default='')),
                ('points', models.PositiveIntegerField(default=10)),
                ('negative_marking_enabled', models.BooleanField(default=False)),
                ('negative_points', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(default='MEDIUM', max_length=20)),
                ('type_config', models.JSONField(default=dict)),
                ('coding_config', models.JSONField(default=dict)),
                ('sql_config', models.JSONField(default=dict)),
                ('tags', models.JSONField(default=list)),
                ('question_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot_usages', to='questions.questionversion')),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='snapshot_questions', to='assessments.assessmentsnapshot')),
            ],
            options={
                'db_table': 'assessment_snapshot_questions',
                'ordering': ['snapshot', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TestAttempt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], db_index=True, default='NOT_STARTED', max_length=20)),
                ('randomization_seed', models.CharField(help_text='Authoritative random seed for deterministic question & option shuffle.', max_length=128)),
                ('question_order', models.JSONField(default=list, help_text='Ordered list of snapshot_question_ids presented to this attempt.')),
                ('option_orders', models.JSONField(default=dict, help_text='Mapping of {snapshot_question_id: [shuffled_option_ids]}.')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.assessment')),
                ('assessment_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='assessments.assessmentsnapshot')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_attempts',
            },
        ),
        migrations.CreateModel(
            name='AttemptAnswer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(db_index=True, max_length=64)),
                ('question_type', models.CharField(max_length=32)),
                ('revision', models.PositiveIntegerField(default=1, help_text='Monotonically increasing version counter preventing out-of-order write races.')),
                ('selected_options', models.JSONField(blank=True, null=True)),
                ('text_response', models.TextField(blank=True, null=True)),
                ('code_response', models.TextField(blank=True, null=True)),
                ('code_language', models.CharField(blank=True, max_length=32, null=True)),
                ('sql_response', models.TextField(blank=True, null=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('last_saved_at', models.DateTimeField(auto_now=True)),
                ('snapshot_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempt_answers', to='assessments.assessmentsnapshotquestion')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.testattempt')),
            ],
            options={
                'db_table': 'attempt_answers',
            },
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['status', 'start_datetime', 'end_datetime'], name='idx_assessment_status_sched'),
        ),
        migrations.AddIndex(
            model_name='assessmentassignment',
            index=models.Index(fields=['student', 'status'], name='idx_assignment_student_status'),
        ),
        migrations.AddConstraint(
            model_name='assessmentassignment',
            constraint=models.UniqueConstraint(fields=('assessment', 'student'), name='unique_assessment_student_assignment'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('assessment', 'question_version'), name='unique_assessment_question_version'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('assessment', 'order'), name='unique_assessment_question_order'),
        ),
        migrations.AddConstraint(
            model_name='assessmentsnapshotquestion',
            constraint=models.UniqueConstraint(fields=('snapshot', 'snapshot_question_id'), name='unique_snapshot_question_id'),
        ),
        migrations.AddIndex(
            model_name='testattempt',
            index=models.Index(fields=['student', 'assessment', 'status'], name='idx_attempt_student_assessment'),
        ),
        migrations.AddConstraint(
            model_name='testattempt',
            constraint=models.UniqueConstraint(fields=('student', 'assessment', 'attempt_number'), name='unique_student_assessment_attempt'),
        ),
        migrations.AddIndex(
            model_name='attemptanswer',
            index=models.Index(fields=['attempt', 'question_id'], name='idx_attempt_question_lookup'),
        ),
        migrations.AddConstraint(
            model_name='attemptanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'snapshot_question'), name='unique_attempt_snapshot_question_answer'),
        ),
    ]
