# Generated by Django 5.1.15 on 2026-09-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='passing_percentage',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Minimum score percentage required to pass the assessment.', max_digits=5),
        ),
    ]
