# Generated by Django 5.1.15 on 2026-09-05 13:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_section_studentprofile_section_and_more'),
        ('assessments', '0002_assessment_passing_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='target_sections',
            field=models.ManyToManyField(blank=True, help_text='Academic sections targeted for this assessment.', related_name='targeted_assessments', to='accounts.section'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='target_students',
            field=models.ManyToManyField(blank=True, help_text='Individual student accounts targeted for this assessment.', related_name='individually_targeted_assessments', to=settings.AUTH_USER_MODEL),
        ),
    ]
